export const moduleConfigs = {
  "operations-center": {
    title: "İşlem Merkezi",
    description: "Queue, retry ve işlem sonuçlarını tek ekrandan yönetim.",
    reports: ["Kuyruk Yoğunluk Raporu", "Retry Sebep Analizi", "İşlem Süre Dağılımı"],
    endpoints: { list: "/operations/jobs", metrics: "/operations/metrics" },
    columns: ["id", "job", "type", "status", "owner", "updated_at", "created_at"],
  },
  approvals: {
    title: "Onay Akışları",
    description: "Bordro yayınlama ve mint öncesi çok adımlı onay yönetimi.",
    reports: ["Onay Süre Raporu", "Onaylayan Bazlı Performans", "Red Nedenleri"],
    endpoints: { list: "/approvals", metrics: "/approvals/metrics" },
    columns: ["id", "request", "status", "assignee", "company_id", "updated_at"],
  },
  compliance: {
    title: "Uyumluluk ve Denetim",
    description: "Audit log, erişim izleri ve regülasyon kontrolleri.",
    reports: ["Audit Trail Raporu", "Yetki İhlali Raporu", "Dışa Aktarım Geçmişi"],
    endpoints: { list: "/compliance/audit-logs", metrics: "/compliance/security-events" },
    columns: ["id", "event", "severity", "actor", "company_id", "updated_at"],
  },
  notifications: {
    title: "Bildirimler",
    description: "Sistem uyarıları, başarısız mint ve operasyonel bildirim merkezi.",
    reports: ["Bildirim Tür Dağılımı", "Kritik Alarm Geçmişi", "Kullanıcı Bildirim Cevabı"],
    endpoints: { list: "/notifications", metrics: "/notifications/metrics" },
    columns: ["id", "message", "channel", "status", "user_id", "updated_at"],
  },
  integrations: {
    title: "Entegrasyonlar",
    description: "ERP/HR sistemleri, webhooklar ve API anahtar yönetimi.",
    reports: ["Webhook Başarı Raporu", "ERP Senkronizasyon Raporu", "API Kullanım Özeti"],
    endpoints: { list: "/integrations", metrics: "/integrations/webhooks/logs" },
    columns: ["id", "name", "type", "status", "updated_at"],
  },
  templates: {
    title: "Şablonlar",
    description: "Bordro NFT metadata, doküman ve imza şablon yönetimi.",
    reports: ["Şablon Kullanım Raporu", "Versiyon Geçiş Raporu", "İmza Şablon Atama Raporu"],
    endpoints: { list: "/templates", metrics: "/templates/metrics" },
    columns: ["id", "name", "version", "status", "updated_at"],
  },
  wallets: {
    title: "Cüzdan Yönetimi",
    description: "Çalışan cüzdanları, doğrulama süreçleri ve ağ uyumluluğu.",
    reports: ["Wallet Doğrulama Raporu", "Ağ Uyumluluk Raporu", "Eksik Wallet Listesi"],
    endpoints: { list: "/wallets", metrics: "/wallets/metrics" },
    columns: ["id", "employee_id", "wallet_address", "network", "status", "updated_at"],
  },
  "bulk-operations": {
    title: "Toplu İşlemler",
    description: "JSON/CSV import, toplu güncelleme ve toplu iş operasyonları.",
    reports: ["Import Sonuç Raporu", "Toplu Güncelleme Hata Raporu", "Batch Performans Raporu"],
    endpoints: { list: "/bulk-operations", metrics: "/bulk-operations/metrics" },
    columns: ["id", "operation", "status", "count", "created_by", "updated_at"],
  },
  "cost-reports": {
    title: "Maliyet ve Ücret Raporları",
    description: "Mint maliyetleri, ağ ücretleri ve şirket bazlı finansal görünüm.",
    reports: ["Şirket Bazlı Maliyet", "Ağ Bazlı Gas Raporu", "Mint Başına Birim Maliyet"],
    endpoints: { list: "/cost-reports/by-company", metrics: "/cost-reports/summary" },
    columns: ["company_id", "company_name", "network", "total_cost", "currency", "updated_at"],
  },
  roles: {
    title: "Yetki ve Roller",
    description: "RBAC yönetimi, rol atamaları ve erişim matrisi.",
    reports: ["Rol Dağılım Raporu", "Yetki Değişim Geçmişi", "Kritik Yetki Erişim Raporu"],
    endpoints: { list: "/roles", metrics: "/roles/metrics" },
    columns: ["id", "name", "guard_name", "users_count", "updated_at"],
  },
  exports: {
    title: "Dışa Aktarım Merkezi",
    description: "CSV/Excel/PDF export, scheduled export ve kanıt dosya yönetimi.",
    reports: ["Export Kullanım Raporu", "Dosya Türü Dağılımı", "Zamanlanmış Job Başarı"],
    endpoints: { list: "/exports", metrics: "/exports/metrics" },
    columns: ["id", "name", "format", "status", "requested_by", "updated_at"],
  },
  "system-health": {
    title: "Sistem Sağlığı",
    description: "API, queue worker, job başarısı ve altyapı sağlığı izleme.",
    reports: ["Uptime Trend Raporu", "API Gecikme Raporu", "Worker Hata Analizi"],
    endpoints: { list: "/system-health/services", metrics: "/system-health/overview" },
    columns: ["id", "service", "metric", "status", "updated_at"],
  },
};
